Fix exclusions
SonarOpenCommunity/sonar-cxx-msbuild-tasks pull request #68
Opened 2019-10-10 12:16 UTC by zabulus

2019-10-10 20:32 UTC, jmecosta requested changes

2019-10-10 20:32 UTC, jmecosta commented on CxxSonarQubeRunner/Options.fs
> -        options.SonarPropsToUse <- GetArgumentClass(this.PropsForBeginStage, this.DepracatedSonarPropsContent, this.HomePath, options.UserSonarScannerCli)
hum, i think u are braking  the load from the sonar properties file... this is what we are using for exclusions. So at the root of your solution you can keep  a sonar-runner.properties and after this it will pickup from there

2019-10-11 07:21 UTC, zabulus commented
But PropsForBeginStage is not used inside GetArgumentClass, therefore I don't see how it breaks anything.

2019-10-11 13:25 UTC, jmecosta commented
Something fishy, since we are using exclusions in our projects. Have to
heck how we do it there. This weekend if having a bit of time can take a
look

On Fri, 11 Oct 2019, 10:21 zabulus, <notifications@github.com> wrote:

> But PropsForBeginStage is not used inside GetArgumentClass, therefore I
> don't see how it breaks anything.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/CxxSonarQubeRunner/pull/68?email_source=notifications&email_token=AAH6HSF6FNJUCBR5KMTYFDDQOASRNA5CNFSM4I7MCATKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7DFEY#issuecomment-540947091>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSAQ7WYZDOUH6J5PFRTQOASRNANCNFSM4I7MCATA>
> .
>

2019-10-12 15:56 UTC, jmecosta commented
we are using this /d:sonar.exclusions=Docs/**,another/**, my local repo is also synced to this one! supose then you are correct, likely some bug from my side. thanks i will merge your pr

2019-10-12 15:56 UTC, merged